"""ethanlog_src — fetch the EthanLog client library (one `.c` + one header)
from `rdkcentral/Dobby` at a pinned commit, hermetically (sha256-pinned),
instead of vendoring copies in-tree.

AAMP links `libethanlog.so.3` (the RDK/Sky container logging shim) when built
with `CMAKE_USE_ETHAN_LOG=ON`. The source is public and tiny — `ethanlog.c`
plus `ethanlog.h`, only libc/POSIX includes — so we source it from upstream at
fetch time and cross-compile it ourselves (see //third_party/ethanlog) rather
than keeping hand-copied files. This replaces both a device-harvested
`libethanlog.so.3` and a hand-authored header stub.

Exposes:
  - `@ethanlog_src//:ethanlog.c`          — the source, for our cc_binary.
  - `@ethanlog_src//:include/ethanlog.h`  — the header file, for sysroot staging.
  - `@ethanlog_src//:headers`             — a cc_library carrying the header with
                                            the right include dir.
"""

# Upstream layout inside rdkcentral/Dobby.
_LIB_PATH = "plugins/EthanLog/client/lib"

_BUILD = """\
# Generated by //bazel/repo_rules:ethanlog_src.bzl — do not edit.
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

# Header with its include dir, so `#include "ethanlog.h"` resolves for both
# ethanlog.c and any consumer. `includes` must live in the repo that owns the
# header for the -I to point at this external tree.
cc_library(
    name = "headers",
    hdrs = ["include/ethanlog.h"],
    includes = ["include"],
)

exports_files(["ethanlog.c", "include/ethanlog.h"])
"""

def _ethanlog_src_impl(ctx):
    base = "https://raw.githubusercontent.com/rdkcentral/Dobby/{}/{}".format(
        ctx.attr.commit,
        _LIB_PATH,
    )
    ctx.download(
        url = base + "/source/ethanlog.c",
        sha256 = ctx.attr.source_sha256,
        output = "ethanlog.c",
    )
    ctx.download(
        url = base + "/include/ethanlog.h",
        sha256 = ctx.attr.header_sha256,
        output = "include/ethanlog.h",
    )
    ctx.file("BUILD.bazel", _BUILD)

ethanlog_src = repository_rule(
    implementation = _ethanlog_src_impl,
    attrs = {
        "commit": attr.string(mandatory = True, doc = "rdkcentral/Dobby commit SHA."),
        "source_sha256": attr.string(mandatory = True, doc = "sha256 of source/ethanlog.c."),
        "header_sha256": attr.string(mandatory = True, doc = "sha256 of include/ethanlog.h."),
    },
)
