"""jsc_deb — source the JavaScriptCore C-API headers + symbol list from pinned
Debian WebKitGTK `.deb`s at fetch time (hermetic, no vendored copies).

`libaampjsbindings.so` links against the classic JavaScriptCore C API
(`<JavaScriptCore/JavaScript.h>` — `JSObjectRef`, `JSContextRef`, …). This rule
fetches:

  - **headers** from `libjavascriptcoregtk-4.1-dev`
    (`usr/include/webkitgtk-4.1/JavaScriptCore/*.h`);
  - **symbols** from `libjavascriptcoregtk-4.1-0` — the exact classic-C-API
    exports of the real runtime `.so`, via `nm -D` (authoritative ABI).

WebKitGTK is the sole distro source: WPE's own `libWPEWebKit-1.1.so.0` exports
only the glib `jsc_*`/`webkit_*` APIs, not the classic `JSObjectRef` C API. The
device's WPE still supplies the same frozen C API at runtime; this only sources
the *build*-time headers + link-stub symbol set. Replaces the hand-copied
headers and hand-frozen `wpe-webkit.syms` in //third_party/jsc.

Host `ar` + `nm` (binutils) are the only host requirements, same as deb_sysroot.
"""

_DATA_TARBALLS = ["data.tar.zst", "data.tar.xz", "data.tar.gz", "data.tar"]

# The 8 classic JSC C-API headers jsbindings needs (BSD/LGPL).
_HEADERS = [
    "JSBase.h",
    "JSContextRef.h",
    "JSObjectRef.h",
    "JSStringRef.h",
    "JSTypedArray.h",
    "JSValueRef.h",
    "JavaScript.h",
    "WebKitAvailability.h",
]

_BUILD = """\
# Generated by //bazel/repo_rules:jsc_deb.bzl — do not edit.
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "headers",
    srcs = glob(["include/JavaScriptCore/*.h"]),
)

exports_files(["wpe-webkit.syms"])
"""

def _unwrap_deb(ctx, ar, deb, outdir):
    """`ar x` a .deb (from repo root) into outdir and extract its data.tar.*."""
    ctx.execute(["mkdir", "-p", outdir])
    res = ctx.execute([ar, "x", "../" + deb], working_directory = outdir)
    if res.return_code != 0:
        fail("jsc_deb: `ar x {}` failed: {}".format(deb, res.stderr))
    for name in _DATA_TARBALLS:
        if ctx.path(outdir + "/" + name).exists:
            ctx.extract(archive = outdir + "/" + name, output = outdir)
            return
    fail("jsc_deb: no data.tar.* found in {}".format(deb))

def _jsc_deb_impl(ctx):
    ar = ctx.which("ar")
    nm = ctx.which("nm")
    if not ar or not nm:
        fail("jsc_deb requires host `ar` and `nm` (binutils) on PATH")

    ctx.download(url = ctx.attr.headers_url, sha256 = ctx.attr.headers_sha256, output = "hdr.deb")
    ctx.download(url = ctx.attr.symbols_url, sha256 = ctx.attr.symbols_sha256, output = "sym.deb")
    _unwrap_deb(ctx, ar, "hdr.deb", "hdr")
    _unwrap_deb(ctx, ar, "sym.deb", "sym")

    # Headers -> include/JavaScriptCore/ (the include prefix //third_party/jsc uses).
    hdr_src = "hdr/usr/include/webkitgtk-4.1/JavaScriptCore"
    ctx.execute(["mkdir", "-p", "include/JavaScriptCore"])
    for h in _HEADERS:
        src = ctx.path(hdr_src + "/" + h)
        if not src.exists:
            fail("jsc_deb: header {} not found under {}".format(h, hdr_src))
        res = ctx.execute(["cp", str(src), "include/JavaScriptCore/" + h])
        if res.return_code != 0:
            fail("jsc_deb: copying {} failed: {}".format(h, res.stderr))

    # Symbols -> wpe-webkit.syms: the classic JS*/kJS* C-API exports of the real
    # runtime .so (nm -D). A superset of what the stub needs — extra exports are
    # harmless for a link stub.
    libdir = ctx.path("sym/usr/lib/arm-linux-gnueabihf")
    so = None
    for entry in libdir.readdir():
        if entry.basename.startswith("libjavascriptcoregtk-4.1.so.0."):
            so = entry
            break
    if not so:
        fail("jsc_deb: libjavascriptcoregtk-4.1 runtime .so not found in the symbols deb")
    res = ctx.execute([nm, "-D", "--defined-only", str(so)])
    if res.return_code != 0:
        fail("jsc_deb: `nm -D` failed: {}".format(res.stderr))
    syms = {}
    for line in res.stdout.splitlines():
        # nm format is "ADDR TYPE NAME"; Starlark split() needs an explicit sep,
        # so split on space and drop the empties from the padded address column.
        fields = [t for t in line.replace("\t", " ").split(" ") if t]
        if len(fields) >= 3:
            name = fields[-1]
            if name.startswith("JS") or name.startswith("kJS"):
                syms[name] = True
    if not syms:
        fail("jsc_deb: no JS*/kJS* symbols extracted from {}".format(so.basename))
    ctx.file("wpe-webkit.syms", "\n".join(sorted(syms)) + "\n")

    ctx.file("BUILD.bazel", _BUILD)

jsc_deb = repository_rule(
    implementation = _jsc_deb_impl,
    attrs = {
        "headers_url": attr.string(mandatory = True, doc = "URL of the libjavascriptcoregtk-*-dev .deb (headers)."),
        "headers_sha256": attr.string(mandatory = True),
        "symbols_url": attr.string(mandatory = True, doc = "URL of the libjavascriptcoregtk-*-0 runtime .deb (symbols via nm)."),
        "symbols_sha256": attr.string(mandatory = True),
    },
)
