"""jsc_deb — source the JavaScriptCore C-API headers + symbol list from pinned
Debian WebKitGTK `.deb`s at fetch time (hermetic, no vendored copies).

`libaampjsbindings.so` links against the classic JavaScriptCore C API
(`<JavaScriptCore/JavaScript.h>` — `JSObjectRef`, `JSContextRef`, …). This rule
fetches:

  - **headers** from `libjavascriptcoregtk-4.1-dev`
    (`usr/include/webkitgtk-4.1/JavaScriptCore/*.h`);
  - **symbols** from `libjavascriptcoregtk-4.1-0` — the exact classic-C-API
    exports of the real runtime `.so`, via `nm -D` (authoritative ABI).

WebKitGTK is the sole distro source: WPE's own `libWPEWebKit-1.1.so.0` exports
only the glib `jsc_*`/`webkit_*` APIs, not the classic `JSObjectRef` C API. The
device's WPE still supplies the same frozen C API at runtime; this only sources
the *build*-time headers + link-stub symbol set. Replaces the hand-copied
headers and hand-frozen `wpe-webkit.syms` in //third_party/jsc.

No host binutils required: Bazel's extractor unwraps the `.deb` ar container, and
the symbol list is derived downstream by //third_party/jsc using the *cross* nm
(the runtime `.so` is ELF32 ARM, which the host's nm cannot be relied on to read).
This rule uses **no host tools at all** — only `ctx.download`, `ctx.extract`,
`ctx.read` and `ctx.file`.
"""

_DATA_TARBALLS = ["data.tar.zst", "data.tar.xz", "data.tar.gz", "data.tar"]

# The 8 classic JSC C-API headers jsbindings needs (BSD/LGPL).
_HEADERS = [
    "JSBase.h",
    "JSContextRef.h",
    "JSObjectRef.h",
    "JSStringRef.h",
    "JSTypedArray.h",
    "JSValueRef.h",
    "JavaScript.h",
    "WebKitAvailability.h",
]

_BUILD = """\
# Generated by //bazel/repo_rules:jsc_deb.bzl — do not edit.
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "headers",
    srcs = glob(["include/JavaScriptCore/*.h"]),
)

# The real WebKitGTK runtime .so, left where the deb put it. //third_party/jsc runs
# the cross nm over this to derive the exported-symbol list for its link stub.
filegroup(
    name = "runtime_so",
    srcs = glob(["sym/usr/lib/arm-linux-gnueabihf/libjavascriptcoregtk-4.1.so.0.*"]),
)
"""

def _unwrap_deb(ctx, deb, outdir):
    """Unwrap a .deb into outdir and extract its data.tar.*.

    No host binutils involved: Bazel's own extractor understands the `ar` container
    a .deb is, so one extract yields debian-binary/control.tar.*/data.tar.* and a
    second unpacks the payload.
    """
    ctx.extract(archive = deb, output = outdir)
    for name in _DATA_TARBALLS:
        if ctx.path(outdir + "/" + name).exists:
            ctx.extract(archive = outdir + "/" + name, output = outdir)
            return
    fail("jsc_deb: no data.tar.* found in {}".format(deb))

def _jsc_deb_impl(ctx):
    ctx.download(url = ctx.attr.headers_url, sha256 = ctx.attr.headers_sha256, output = "hdr.deb")
    ctx.download(url = ctx.attr.symbols_url, sha256 = ctx.attr.symbols_sha256, output = "sym.deb")
    _unwrap_deb(ctx, "hdr.deb", "hdr")
    _unwrap_deb(ctx, "sym.deb", "sym")

    # Headers -> include/JavaScriptCore/ (the include prefix //third_party/jsc uses).
    # Copied through ctx.read/ctx.file rather than host `cp` so this rule needs no
    # host tools; ctx.file creates the parent dirs. These are the 8 classic JSC C-API
    # headers and are pure US-ASCII, so the round-trip is byte-exact.
    hdr_src = "hdr/usr/include/webkitgtk-4.1/JavaScriptCore"
    for h in _HEADERS:
        src = ctx.path(hdr_src + "/" + h)
        if not src.exists:
            fail("jsc_deb: header {} not found under {}".format(h, hdr_src))
        ctx.file("include/JavaScriptCore/" + h, ctx.read(src), executable = False)

    # The runtime .so is left in place and exposed as :runtime_so; the symbol list is
    # derived from it by //third_party/jsc using the *cross* nm, because reading an
    # ELF32 ARM object with the host's nm is not something we can rely on (see the
    # :nm filegroup in //third_party/bootlin:toolchain.BUILD.bazel). Fail here rather
    # than let a glob silently match nothing downstream.
    libdir = ctx.path("sym/usr/lib/arm-linux-gnueabihf")
    if not [e for e in libdir.readdir() if e.basename.startswith("libjavascriptcoregtk-4.1.so.0.")]:
        fail("jsc_deb: libjavascriptcoregtk-4.1 runtime .so not found in the symbols deb")

    ctx.file("BUILD.bazel", _BUILD)

jsc_deb = repository_rule(
    implementation = _jsc_deb_impl,
    attrs = {
        "headers_url": attr.string(mandatory = True, doc = "URL of the libjavascriptcoregtk-*-dev .deb (headers)."),
        "headers_sha256": attr.string(mandatory = True),
        "symbols_url": attr.string(mandatory = True, doc = "URL of the libjavascriptcoregtk-*-0 runtime .deb (symbols via nm)."),
        "symbols_sha256": attr.string(mandatory = True),
    },
)
